"""auto add users table

Revision ID: 5a3fbf9afd9d
Revises: 933bc3fc7535
Create Date: 2022-04-21 15:00:40.474697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a3fbf9afd9d'
down_revision = '933bc3fc7535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
