"""auto add posts table

Revision ID: 933bc3fc7535
Revises: a1a5fde463ba
Create Date: 2022-04-21 14:58:48.780696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '933bc3fc7535'
down_revision = 'a1a5fde463ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
